## Neural Networks from Scratch
### Chapter 2

### 2.1 My very first neuron

In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = sum([inputs[i]*weights[i] for i in range(len(inputs))] + [bias])
print(output)

4.8


### 2.2 Layers

In [4]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output1 = sum([inputs[i]*weights1[i] for i in range(len(inputs))] + [bias1])
output2 = sum([inputs[i]*weights2[i] for i in range(len(inputs))] + [bias2])
output3 = sum([inputs[i]*weights3[i] for i in range(len(inputs))] + [bias3])

outputs = [output1, output2, output3]

print(outputs)

[4.8, 1.21, 2.385]


#### 2.2.1 Using matrices and for loops

In [5]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]
outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = sum([inputs[i]*neuron_weights[i] for i in range(len(inputs))] + [neuron_bias])
    outputs.append(neuron_output)
    
print(outputs)

[4.8, 1.21, 2.385]


#### 2.2.1 Using numpy

In [8]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

outputs = np.dot(weights, inputs) + biases
    
print(outputs)

[4.8   1.21  2.385]


#### 2.2.1 Using numpy and batches as inputs

In [9]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases
    
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
