## Neural Networks from Scratch
### Chapter 5

In [1]:
from IPython.display import Image, display
from IPython.core.display import HTML 

### 5.1 Cross-Entropy Loss

<img src="https://i.stack.imgur.com/gNip2.png" width="400" height="200" align="center">

#### Implementation 1

In [16]:
from math import log


softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

-(target_output[0]*log(softmax_output[0]) + target_output[1]*log(softmax_output[1]) + target_output[2]*log(softmax_output[2])), -np.dot(target_output, np.log(softmax_output))

(0.35667494393873245, 0.35667494393873245)

In [66]:
import numpy as np

softmax_outputs = np.array([[0.7, 0.1, 0.2], [0.1, 0.5, 0.4], [0.02, 0.9, 0.08]])
class_targets = np.array([0, 1, 1])

-np.dot(class_targets, np.log(softmax_outputs))

array([6.2146081 , 0.7985077 , 3.44201938])

In [35]:
for targ_idx, distribution in zip(class_targets, softmax_outputs):
    print(distribution[targ_idx])

0.7
0.5
0.9


In [36]:
print(softmax_outputs[[0, 1, 2], class_targets])

[0.7 0.5 0.9]


In [37]:
print(softmax_outputs[
range(len(softmax_outputs)), class_targets
])

[0.7 0.5 0.9]


In [38]:
print(-np.log(softmax_outputs[range(len(softmax_outputs)), class_targets]))


[0.35667494 0.69314718 0.10536052]


In [40]:
softmax_outputs.shape

(3, 3)

In [41]:
softmax_outputs

array([[0.7 , 0.1 , 0.2 ],
       [0.1 , 0.5 , 0.4 ],
       [0.02, 0.9 , 0.08]])

In [53]:
np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])

array([-0.35667494, -0.69314718, -0.10536052])

In [55]:
neg_log = -np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])
average_loss = np.mean(neg_log)

print(average_loss)

0.38506088005216804


### 5.2 Classes Loss and LossCategoricalCrossentropy

In [5]:
import numpy as np

In [57]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [76]:
class LossCategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        n_samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(n_samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

In [77]:
loss_function = LossCategoricalCrossentropy()
loss = loss_function.calculate(softmax_outputs, class_targets)
print(loss)

0.38506088005216804


### 5.3 Accuracy

In [88]:
import numpy as np

softmax_outputs = np.array([[0.7, 0.2, 0.1], [0.5, 0.1, 0.4], [0.02, 0.9, 0.08]])
class_targets = np.array([0, 1, 1])

predictions = np.argmax(softmax_outputs, axis=1)

if len(class_targets.shape) == 2:
    class_targets = np.argmax(class_targets, axis=1)

accuracy = np.mean(predictions==class_targets)
print('acc:', accuracy)

acc: 0.6666666666666666
