## Neural Networks from Scratch
### Chapter 4

In [1]:
from IPython.display import Image, display
from IPython.core.display import HTML 

### 4.1 ReLU Activation Function

<img src="https://assets-global.website-files.com/5d7b77b063a9066d83e1209c/60be1b236a3731df9b1d43c9_math-20210607%20(11).png" width="300" height="200" align="center">

#### Implementation 1

In [2]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
    output.append(i) if i > 0 else output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


#### Implementation 2

In [3]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
    output.append(max(0, i))
    
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


#### Implementation 3

In [4]:
import numpy as np

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = np.maximum(0, inputs)

print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


### 4.2 Class ReLU + DenseLayerClass

In [5]:
import numpy as np

In [6]:
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [7]:
class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        self.output = np.dot(np.array(inputs), self.weights) + self.biases

In [8]:
from nnfs.datasets import spiral_data

X, y = spiral_data(samples=100, classes=3)

dense1 = LayerDense(2, 3) # Create Dense Layer Network with 2 inputs and 3 outputs

activation1 = ActivationReLU() # Create the ReLU Object

dense1.forward(X) # Apply forward pass

activation1.forward(dense1.output) # Apply the ReLU func

In [9]:
print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.17485058e-04 4.27698114e-05]
 [0.00000000e+00 2.19584305e-04 1.13841189e-05]
 [0.00000000e+00 3.21584118e-04 0.00000000e+00]
 [2.35476097e-04 3.27625262e-04 0.00000000e+00]]


### 4.3 Softmax Activation Function

<img src="https://lh6.googleusercontent.com/3vcfJ5hJhsMZAMFIbQOEycfVW1t6rh1CXt62DeMk8RPPXVzV4vCcURNm_z_F7618uAeSHT7qT7wE_UiK5Ic0b-Eeuunn6iTGeHWbpAaUAP6-G2ePubeGWCb4_TmSapeaimZqvuUs" width="300" height="200" align="center">

In [10]:
layer_outputs = [4.8, 1.21, 2.385]

exp_values = []
for value in layer_outputs:
    exp_values.append(np.exp(value))

exp_values, exp_values/sum(exp_values)

([121.51041751873485, 3.3534846525490236, 10.859062664920515],
 array([0.89528266, 0.02470831, 0.08000903]))

#### Vectorized

In [11]:
layer_outputs = [4.8, 1.21, 2.385]
np.exp(layer_outputs)/np.sum(np.exp(layer_outputs))

array([0.89528266, 0.02470831, 0.08000903])

In [12]:
layer_outputs = np.array([[4.8, 1.21, 2.385], [8.9, -1.81, 0.2], [1.41, 1.051, 0.026]])
np.exp(layer_outputs)/np.sum(np.exp(layer_outputs), axis=1, keepdims=True)

array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [23]:
layer_outputs = np.array([[4.8, 1.21, 2.385], [8.9, -1.81, 0.2], [1.41, 1.051, 0.026]])
exp_values = np.exp(layer_outputs - np.max(layer_outputs, axis=1, keepdims=True))
exp_values/np.sum(exp_values, axis=1, keepdims=True)

array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

#### 4.3.1 Class Softmax

In [20]:
class ActivationSoftmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        self.output = exp_values/np.sum(exp_values, axis=1, keepdims=True)

In [25]:
softmax = ActivationSoftmax()

softmax.forward([[1, 2, 3]])
print(softmax.output)

softmax.forward([[-2, -1, 0]])  #-2
print(softmax.output)

softmax.forward([[-4, -3, -2]]) #-5 
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]
[[0.09003057 0.24472847 0.66524096]]
[[0.09003057 0.24472847 0.66524096]]
